-- 년,월,성별 별로 상품을 구매한 회원수 집계
-- 결과 년 월 성별 기준으로 오름차순, 성별정보없으면 결과에서 제외
-- USER_INFO와 ONLINE_SALE을 조인하고
-- WHERE절을 통해서 성별이 NULL인 애들을 없앤다.
SELECT
YEAR(o.SALES_DATE) YEAR,
MONTH(o.SALES_DATE) MONTH,
u.GENDER,
COUNT(DISTINCT u.USER_ID) USERS
FROM USER_INFO u JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER
ORDER BY YEAR, MONTH, GENDER;