-- 재귀함수
WITH RECURSIVE HOURS AS (
    SELECT 0 AS NUM 
    UNION ALL
    SELECT NUM+1 FROM HOURS
    WHERE NUM < 23
)

SELECT 
HOURS.NUM AS HOUR, 
COUNT(AO.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN HOURS ON EXTRACT(HOUR FROM AO.DATETIME) = HOURS.NUM
GROUP BY HOURS.NUM
ORDER BY HOUR

-- 23.11.27 표현2
-- 0-23시
-- 각 시간대별 입양건수
-- 시간순 정렬
-- + 없는 시간대는 0으로 해야한다.
SET @HOUR = -1;

SELECT
(@HOUR := @HOUR + 1) AS HOUR,
(SELECT COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)=@HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23;