-- 음식종류별로 즐겨찾기수가 가장 많은 식당
-- 음식종류, ID, 식당이름, 즐겨찾기수
-- 음식종류 내림차순
SELECT
r.FOOD_TYPE,
r.REST_ID,
r.REST_NAME,
r.FAVORITES
FROM
REST_INFO r JOIN (
    SELECT
    FOOD_TYPE,
    MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FOOD_TYPE DESC
) s
ON r.FOOD_TYPE = s.FOOD_TYPE AND r.FAVORITES = s.FAVORITES
ORDER BY r.FOOD_TYPE DESC;

-- 23.11.27 다시풀이
SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (
    -- 음식종류, 음식종류의 최대 즐겨찾기 수
    SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) A JOIN REST_INFO B
WHERE B.FOOD_TYPE = A.FOOD_TYPE AND B.FAVORITES = A.MAX_FAV
ORDER BY B.FOOD_TYPE DESC;