-- 상반기
-- 아이스크림 성분 타입, 성분 타입에 대한 아이스크림의 총 주문량
-- 작은 순서대로
SELECT
i.INGREDIENT_TYPE,
SUM(f.TOTAL_ORDER) TOTAL_ORDER
FROM
FIRST_HALF f JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;

-- 23.11.27 다시풀기
-- 상반기
-- 아이스크림 성분 타입, 타입에 대한 아이스크림 총주문량
-- 총주문량이 작은 순서대로 조회
SELECT
i.INGREDIENT_TYPE,
SUM(f.TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF f JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY 2;