-- 2022년 1월 카테고리별 도서 판매량 합산
-- 카테고리, 총판매량 리스트 출력
SELECT
CATEGORY,
SUM(SALES) TOTAL_SALES
FROM BOOK b JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY b.CATEGORY
ORDER BY CATEGORY;