-- 2022년 1월 카테고리별 도서 판매량 합산
-- 카테고리, 총판매량 리스트 출력
SELECT
CATEGORY,
SUM(SALES) TOTAL_SALES
FROM BOOK b JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY b.CATEGORY
ORDER BY CATEGORY;

-- 23.11.27 다시풀기
-- 2022년 1월
-- 카테고리 별 도서 판매량
-- 카테고리, 총판매량
-- 카테고리명 오름차순
SELECT
b.CATEGORY,
SUM(s.SALES) TOTAL_SALES
FROM BOOK b JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID AND s.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY b.CATEGORY
ORDER BY 1;