-- 2022년 10월 5일 등록된 중고거래
-- 게시글 ID, 작성자 ID, 게시글 제목, 가격, 거래상태
-- SALE -> 판매중, RESERVED -> 예약중, DONE -> 거래완료
-- 게시글 ID 내림차순
SELECT
BOARD_ID,
WRITER_ID,
TITLE,
PRICE,
CASE WHEN STATUS = "SALE"
    THEN "판매중"
    WHEN STATUS = "RESERVED"
    THEN "예약중"
    WHEN STATUS = "DONE"
    THEN "거래완료"
    END STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = "2022-10-05"
ORDER BY BOARD_ID DESC;

-- 아래와 같이 표현도 가능하다.
SELECT
BOARD_ID,
WRITER_ID,
TITLE,
PRICE,
CASE STATUS
    WHEN "SALE" THEN "판매중"
    WHEN "RESERVED" THEN "예약중"
    WHEN "DONE" THEN "거래완료"
    END STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = "2022-10-05"
ORDER BY BOARD_ID DESC;