-- 2022년 9월(대여 시작일)
-- 대여기간이 30일 이상 -> 장기대여
-- 그렇지 않으면 -> 단기대여
-- 대여기록 ID 내림차순
SELECT
HISTORY_ID,
CAR_ID,
DATE_FORMAT(START_DATE, "%Y-%m-%d") START_DATE,
DATE_FORMAT(END_DATE, "%Y-%m-%d") END_DATE,
CASE WHEN DATE_ADD(START_DATE, INTERVAL 29 DAY) <= END_DATE -- 당일도 포함해야해서 29DAY해야함
    THEN "장기 대여"
    ELSE "단기 대여"
    END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN "2022-09-01" AND "2022-09-30"
ORDER BY HISTORY_ID DESC;

-- DATEDIFF로 아래와 같이 표현할 수 있다.
SELECT
HISTORY_ID,
CAR_ID,
DATE_FORMAT(START_DATE, "%Y-%m-%d") START_DATE,
DATE_FORMAT(END_DATE, "%Y-%m-%d") END_DATE,
CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
    THEN "장기 대여"
    ELSE "단기 대여"
    END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN "2022-09-01" AND "2022-09-30"
ORDER BY HISTORY_ID DESC;