-- 세단 자동차들
-- 10월 대여를 시작한 기록이 있는 자동차 ID
-- 중복X, 자동차 ID를 기준으로 내림차순
SELECT DISTINCT(r.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR r 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON r.CAR_ID = h.CAR_ID
WHERE r.CAR_TYPE = "세단" AND MONTH(h.START_DATE) = 10
ORDER BY r.CAR_ID DESC;