-- 평균대여기간이 7일 이상인 자동차들
-- 자동차ID, 평균대여기간(AVERAGE_DURATION)
-- 평균대여기간 소수점 둘째자리 반올림
-- 평균대여기간 내림차순, 자동차ID 내림차순
SELECT
CAR_ID,
ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;