-- 15:56~
-- 2021년 출판, 인문 카테고리
-- ID, 출판일
-- 출판일 오름차순
SELECT
b.BOOK_ID,
DATE_FORMAT(b.PUBLISHED_DATE, "%Y-%m-%d") PUBLICSHED_DATE
FROM BOOK b
WHERE YEAR(b.PUBLISHED_DATE) = 2021 AND b.CATEGORY = "인문"
ORDER BY b.PUBLISHED_DATE ASC;